Updated SPP into new prefetcher format
ChampSim/ChampSim pull request #495
Opened 2024-09-11 22:26 UTC by maccoymerrell

2024-09-11 22:28 UTC, maccoymerrell commented
Legacy SPP does not work. This is a port of the old SPP into the new prefetcher format (which works).

2024-09-12 02:53 UTC, ngober requested changes
A few organizational suggestions, including one that I know is a bug.

2024-09-12 02:53 UTC, ngober commented on prefetcher/spp_dev/spp_dev.h
> +namespace spp{
Should these be `constexpr static` members of `spp_dev`?

2024-09-12 02:53 UTC, ngober commented on prefetcher/spp_dev/spp_dev.cc
> +spp_dev::SIGNATURE_TABLE ST;
These should _definitely_ be members of `spp_dev`. Otherwise they are shared across all instances. (This is a bug in the legacy also).

2024-09-12 02:53 UTC, ngober commented on prefetcher/spp_dev/spp_dev.h
> +}; // namespace spp
```suggestion
};
```

2024-09-12 22:39 UTC, merged