Added vmem randomization in config
ChampSim/ChampSim pull request #538
Opened 2024-11-08 18:44 UTC by maccoymerrell

I have had this change on my research forks for quite a while. I was doing it via command-line argument, but the way ChampSim is set up, this always guaranteed that the main page structure for the virtual memory would be linear-mapped since they are assigned immediately, before command-line arguments can be parsed.

This instead uses a config option to control it, as a list of two parameters [randomization_enabled,randomization_seed].
Since this is passed to the VMEM constructor, we can avoid the page tables getting linear-mapped when we don't want it.
[false,n] == disabled randomization
[true,n] == enabled randomization at seed n.

2024-11-08 23:00 UTC, ngober requested changes

2024-11-09 03:44 UTC, maccoymerrell commented
Here's what's changed:
1. There is a single vmem constructor with an std::optional randomization_seed argument at the end. It has a default value of {} if not specified.
2. There is a single value passed in the config for randomization. If it is false, '{}' is used within the vmem constructor for randomization seed, else (true or an integer) it is passed as an integer value.
3. Tests have been altered to use the constructor without defining the randomization seed. DRAM still had to be changed for these tests, as vmem cannot support memories smaller than 1 MiB. I don't know what was allowing these tests to pass before, but it shouldn't have been possible since no physical memory should have been available.
4. An assertion has been added to enforce that DRAM > 1 MiB.

2024-11-09 20:30 UTC, ngober commented on test/cpp/src/092-ptw-builder.cc
> +  MEMORY_CONTROLLER dram{champsim::chrono::picoseconds{3200}, champsim::chrono::picoseconds{6400}, std::size_t{18}, std::size_t{18}, std::size_t{18}, std::size_t{38}, champsim::chrono::microseconds{6
What is the purpose of these edits? They don't seem to have anything to do with the patch.

2024-11-09 20:40 UTC, ngober approved these changes
I generally disagree with the choice to use a default constructor argument, see [here](https://quuxplusone.github.io/blog/2020/04/18/default-function-arguments-are-the-devil/), particularly the points about overload sets. In my opinion, C++ has function overloads for exactly this purpose, and it's better for code health. But, I don't feel it's necessary to labor on that point. If you're satisfied, I'm satisfied.

2024-11-09 21:31 UTC, maccoymerrell commented
My reasoning behind this was that with the overloaded constructor approach we would have two constructors with identical code to maintain except for the initialization of the randomization_seed member in one over the other.
Unless there is a way to reuse the constructor declaration for definitions?

I have altered the code to use two different constructors instead, and tried to minimize the code inside each constructor.

2024-11-09 21:36 UTC, ngober commented
You mean something like a [delegating constructor](https://en.cppreference.com/w/cpp/language/constructor#Delegating_constructor)?

2024-11-09 21:39 UTC, maccoymerrell commented
Can't use that, as we need to initialize the member variable (randomization_seed)  _before_ calling the constructor for it to work, or shuffle_pages() isn't going to shuffle because randomization_seed is not set yet. GCC was spamming errors about that.

2024-11-09 21:43 UTC, maccoymerrell commented
Hold up I can do it backwards though.

2024-11-09 22:45 UTC, ngober commented
I'm rerunning that check. Looks like something went wrong with `curl | xz`.

2024-11-10 03:28 UTC, ngober commented on src/vmem.cc
> +  fmt::print("[VMEM] Freed {} ppages\n",ppage_free_list.size());
This prints every time. Is this intentional? It feels like a debug statement. Also L66.

2024-11-10 17:59 UTC, merged